ALLOWED_COMMANDS = {
    "ls", "cat", "head", "tail", "grep", "find", "wc", "echo",
    "mkdir", "touch", "cp", "mv", "rm",
    "python3", "python", "pip", "pip3",
    "node", "npm", "npx",
    "git",
    "curl", "wget",
    "ps", "top", "htop",
    "df", "du", "free",
    "uname", "whoami", "date", "which", "env", "printenv",
    "tar", "gzip", "gunzip", "zip", "unzip",
    "chmod", "chown",
    "sort", "uniq", "cut", "awk", "sed", "tr",
    "ping", "host", "dig",
    "sudo",
    "apt", "apt-get", "dpkg",
    "systemctl", "service",
    "journalctl",
    "docker",
    "ip", "ss", "netstat", "iptables",
}

BLOCKED_PATTERNS = [
    "rm -rf /",
    "rm -rf /*",
    "chmod 777 /",
    "dd if=",
    "mkfs",
    "> /dev/",
    "nc ",
    "ncat ",
    "socat ",
    "telnet ",
    "/etc/shadow",
    "eval(",
    "exec(",
    ":(){",  # fork bomb
    "shutdown",
    "reboot",
    "halt",
    "init 0",
    "init 6",
]

BLOCKED_PATH_PREFIXES = [
    "/proc/kcore",
    "/dev/mem",
    "/dev/kmem",
    "/boot",
]
